version: '3.7'
services:
  php:
    container_name: symf-test-php
    build: docker/php
    image: symf-test-php
    ports:
      - "9000:9001"
    volumes:
      - ./:/var/www/symf-test:cached
    links:
      - db
  db:
    container_name: symf-test-db
    build: docker/db
    image: symf-test-db
    environment:
      - MYSQL_DATABASE=symfony
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
      - MYSQL_PASSWORD=
    volumes:
      - ./docker/db/.mysql:/var/lib/mysql
    ports:
      - "3306:3306"
  nginx:
    container_name: symf-test-nginx
    build: docker/nginx
    image: symf-test-nginx
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites/:/etc/nginx/sites-available
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d
    ports:
      - "8087:80"
    links:
      - php
    depends_on:
      - php
      - db